---
- name: Install PHP and its modules
  apt:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - php7.3
      - php7.3-cli
      - php7.3-curl
      - php7.3-gd
      - php-imagick
      - php-xdebug
      - php7.3-mysql
      - php7.3-xmlrpc
      - php7.3-xml
      - php7.3-mbstring


- name: Install PHP config customizations
  copy:
    src: "{{ item }}"
    dest: /etc/php/7.3/mods-available/{{ item }}
    owner: root
    group: root
    force: yes
  with_items:
    - virtualpress-php-settings.ini
    - virtualpress-xdebug-settings.ini

- name: Activate PHP config customizations
  file:
    src: /etc/php/7.3/mods-available/{{ item }}
    path: /etc/php/7.3/fpm/conf.d/999-{{ item }}
    state: link
  with_items:
    - virtualpress-php-settings.ini
    - virtualpress-xdebug-settings.ini
  notify:
    - restart php

- name: Setup FPM pools for named sites
  template:
    src: pool.conf
    dest: /etc/php/7.3/fpm/pool.d/wordpress.conf
  notify:
    - restart php
